#:schema https://yazi-rs.github.io/schemas/keymap.json

[mgr]
prepend_keymap = [
  # 默认不显示隐藏文件，但搜索文件名时仍能找到隐藏文件（fd）
  { on = "s", run = "search --via=fd --args='--hidden'", desc = "Search files by name via fd (incl. hidden)" },
  # 搜索文件内容时也包含隐藏文件（rg）
  { on = "S", run = "search --via=rg --args='--hidden'", desc = "Search files by content via rg (incl. hidden)" },
]
